runtime: php
env: flex

runtime_config:
  document_root: public
  enable_stackdriver_integration: true
  
# Ensure we skip ".env", which is only for local development
skip_files:
 - .env

env_variables:
  # Put production environment variables here.
  APP_KEY: base64:MMML5a2xeUoOPm4KPKLlUrnJdLz67edC8XCLpAGtVPU=
  # values obtained when configuring your Cloud SQL instance.
  DB_CONNECTION: mysql  
  DB_HOST: 10.110.240.3
  DB_DATABASE: testing_agence
  DB_USERNAME: agence-user
  DB_PASSWORD: hf!3#76g*191